import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const godo = localFont({
  src: [
    {
      path: "./assets/fonts/GodoB.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./assets/fonts/GodoM.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-godo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${godo.variable}`}>{children}</body>
    </html>
  );
}
